name: OSAS
version: 0
author: Old School Minecraft
main: net.oldschoolminecraft.osas.OSAS
commands:
    register:
        description: Register an account
        usage: /register <password>
    login:
        description: Login to your account
        usage: /login <password>
    passwd:
        description: Change your password
        usage: /passwd <old> <new>
        aliases:
            - pwd
    deluser:
        description: Delete an account
        usage: /deluser <username>
        permission: osas.deluser
        default: op
dependencies:
    - 'org.json:json:20180813'
    - 'com.fasterxml.jackson.core:jackson-databind:2.10.0'